Adding SDK documentation for message endpoints
getzep/docs.getzep.com pull request #92
Opened 2023-12-11 22:38 UTC by petergarbers

2023-12-11 23:44 UTC, danielchalef requested changes

2023-12-11 23:44 UTC, danielchalef commented on docs/sdk/chat_history/messages.md
> +The `SessionID` is a string key that access arbritrary identifies. Related data you'd like to store can be persisted as metadata.
think this needs a reread.

2023-12-11 23:44 UTC, danielchalef commented on docs/sdk/chat_history/messages.md
> +You may not update the content of messages, and can only change the metadata.
`Currently, updating message content is not supported. You may, however, update a message's metadata.`

2023-12-12 00:06 UTC, petergarbers commented on docs/sdk/chat_history/messages.md
> +You may not update the content of messages, and can only change the metadata.
This is much better

2023-12-14 23:33 UTC, danielchalef approved these changes
lgtm

2023-12-14 23:34 UTC, merged